run_number=$1

CUDA_VISIBLE_DEVICES=$run_number torchrun --nproc_per_node=1 --master_port=12${run_number}3 examples/reward_modeling.py \
  --fp16 False \
  --bf16 True \
  --seed $run_number \
  --model_name_or_path "/scr-ssd/ahmedah/alp/opt1b-sft-shp/" \
  --dataset_name "stanfordnlp/SHP" \
  --output_dir "/scr-ssd/ahmedah/models/opt1b-rwl-shp-${run_number}/" \
  --model_max_length 2048 \
  --num_train_epochs 5 \
  --per_device_train_batch_size 8 \
  --per_device_eval_batch_size 4 \
  --gradient_accumulation_steps 16 \
  --eval_steps 100 \
  --save_strategy "steps" \
  --save_steps 1000000000 \
  --save_total_limit 1 \
  --learning_rate 3e-6 \
  --weight_decay 0.0 \
  --warmup_ratio 0.03 \
  --lr_scheduler_type "cosine" \
  --evaluation_strategy "steps" \
  --logging_steps 10 \
  --wandb_project "alpaca_farm" \
  --run_name "rl-ensemble-${run_number}" \
  --fsdp "full_shard auto_wrap" \
  --fsdp_transformer_layer_cls_to_wrap "OPTDecoderLayer" \
  --tf32 False \
  --flash_attn True \
  --ddp_timeout 1800 \
  --initialize_model_on_cpu True
